### PR TITLE
doc: adopt getting-started guide

### PR DESCRIPTION
**Pull request by yqlbu**
## Summary

Move the `Usage` section to the `Getting-started` section for a cleaner look.

## Proposed file structure

```
./docs
├── getting-started
│   ├── kernel-upgrade.md
│   └── README.md
└── ...

N directories, N files
```

## Preview

https://github.com/yqlbu/dae/tree/docs

## Changelogs

- [x] Move the `Getting-started` section under `./docs`.
- [x] Add support for the `Kernel` upgrade guide.

### CODE REVIEW

**Comment by mzz2017** [comment]
Looks good. But where is the BTF related content?

**Comment by yqlbu** [comment]
> Looks good. But where is the BTF related content?

IDK. I think somebody else is working on it.

**Comment by mzz2017** [comment]
I saw that you deleted the relevant content, can you keep them temporarily?

**Comment by yqlbu** [comment]
> I saw that you deleted the relevant content, can you keep them temporarily?

Resolved in [3e40e2c](https://github.com/v2rayA/dae/pull/21/commits/3e40e2c1cb461721a5e5bc646b841b742e8a3299)

**Comment by mzz2017** [comment]
I do not see BTF content, could you please check again?

**Comment by mzz2017** [comment]
Good job~ Thanks for your contribution

**Pull request merged**
